- hosts: "localhost"
  become: true
  become_user: root
  vars_files:
    - ../vars/certs.json
  tasks:
    - name: "Setup Let's Encrypt prerequisites"
      include_tasks: certs/setup.yaml
    - name: "Gather Let's Encrypt certificates"
      include_tasks: certs/request.yaml
      loop: "{{ requests }}"

- hosts: ssl
  become: true
  become_user: root
  vars_files:
    - ../vars/certs.json
  tasks:
    - name: "Deploy ssl certificate files"
      include_tasks: certs/deploy.yaml
      loop: "{{ requests }}"
